name: 'DiffMasterFlex'
author: 'selfagency'
description: 'Get a list of files that differ between the specified commit and Git ref'
branding:
  icon: 'layers'
  color: 'blue'
inputs:
  sha:
    description: 'SHA against which to diff'
    required: false
    type: string
  ref:
    description: 'Git ref against which to diff'
    required: false
    type: string
outputs:
  changed:
    description: Whether there were any changes
    type: boolean
  diff:
    description: List of changed files
    type: string
runs:
  using: 'node16'
  main: 'dist/index.cjs'
