name: Test
on:
  push:
    branches:
      - dev
jobs:
  test_action:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Diff
        id: diff
        uses: 'selfagency/diffmasterflex@main'

      - run: |
          echo ${{ steps.diff.outputs.changed }}
          echo ${{ steps.diff.outputs.diff }}

